### PR TITLE
Cleanup X connections on disconnect

### PR DESCRIPTION
**Pull request by Stebalien**
If the server disconnects from us (e.g., exits), use the process sentinel to cleanup the connection object and mark it as disconnected. Otherwise, all the "is connected" checks in EXWM aren't very useful.

This makes it possible to call `(exwm-exit)` followed by `(exwm-init)` after X crashes to restart exwm. Otherwise, `exwm-exit` errors.

* xelb.el (xcb:-connection-sentinel): Define a sentinel function that marks the connection as disconnected on disconnect.
  (xcb:-connect): Bind the sentinel function.
  (xcb:disconnect): Ignore connection errors on disconnect (in case we're already disconnected).

### CODE REVIEW

**Comment by minad** [comment]
Interesting. How do you use this? I start Emacs via `exec emacs` in my `.xsession`, such that X will certainly kill Emacs when it crashes. But X never has never crashed in years on my system.

**Comment by Stebalien** [comment]
I run Emacs as a daemon and use `emacsclient` to start exwm. I don't _usually_ want to restart X, but it's nice to be able to (e.g., on if I update something, want to change some config, etc.).

**Review by minad — APPROVED** [review]

**Comment by minad** [comment]
This PR looks good and ready to merge.

> I run Emacs as a daemon and use `emacsclient` to start exwm.

Just out of interest - what are the advantages of starting Emacs as a daemon in contrast to the simpler setup where Emacs is started from the xsession script? Does this enable certain additional use cases? Restarting X is one use case, but this doesn't too happen often.

**Comment by Stebalien** [comment]
> Just out of interest - what are the advantages of starting Emacs as a daemon in contrast to the simpler setup where Emacs is started from the xsession script? Does this enable certain additional use cases? Restarting X is one use case, but this doesn't too happen often.

I started doing it before I used EXWM. But I kept at it because I manage most of my session with systemd. I don't gain any real benefits (automatic crash restarting, CPU scheduling priorities, but not much else). But I like it...

**Pull request merged**
