### PR TITLE
Replace deprecated lsh with ash

### LINKED ISSUE #1: lsh -> ash compilation warnings
The Emacs byte compiler warns about the usage of `lsh`. It suggests the function `ash` as alternative, which is subtly different. We should check this and use `ash` if possible. cc @Stebalien

### PR DESCRIPTION
**Pull request by minad**
~~~
Replace deprecated `lsh' with `ash'

The functions differ in their behavior for right shifts (negative argument
COUNT) for negative values. The replaced calls are either left shifts or pass a
positive value; as such they are not affected.

* xcb-types.el: (xcb:-pack-*): `lsh' to `ash'. Argument positive (unsigned).
  (xcb:-unpack-*): `lsh' to `ash'. Left shifts.
  (xcb:-f*-to-binary*, xcb:-binary*-to-f*): `lsh' to `ash'. Argument positive.
* xelb-gen (xelb-parse-bit): `lsh' to `ash'. Left shift.
  (xelb-parse-op): `lsh' to `ash'. Left shift.
* xcb-keysyms.el: (xcb:keysyms:-update-modkeys): `lsh' to `ash'. Left shift.
  (xcb:keysyms:keycode->keysym): `lsh' to `ash'. Arguments modifiers and
  group-info positive?
~~~

Fixes #1

### CODE REVIEW

**Comment by minad** [comment]
@Stebalien Do you think it is safe enough to merge this? I run it locally, so far without issues.

**Comment by Stebalien** [comment]
Eh, probably. If you didn't see any immediate issues, I doubt any more testing will help.

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
(and it'll be nice to get rid of all the warnings)

**Comment by minad** [comment]
Okay, thanks. Let's go then.

**Pull request merged**
